content: /Users/nico/Documents/install
script: start.sh
output:
  path: pcUtils.sh
  need_root: true
compression:
  method: gz
  level: 9
  encrypted: true
  encryption_tool: openssl
exclude:
  patterns:
  - '*.bak'
  - '*.egg-info/'
  - '*.log'
  - '*.pyc'
  - '*.pyo'
  - '*.spec'
  - '*.swp'
  - '*.tmp'
  - '*~'
  - .DS_Store
  - ._*
  - .cvs/
  - .env
  - .git
  - .git/
  - .hg/
  - .idea/
  - .project
  - .settings/
  - .svn/
  - .venv/
  - .vscode/
  - Thumbs.db
  - __pycache__/
  - build/
  - dist/
  - env/
  - venv/
  ignore_case: true
hooks:
  pre_build: []
  post_build: []
update:
  enabled: true
  version_url: http://localhost/version.json
  package_url: http://localhost/pcUtils.sh
  version_file_path: /Library/WebServer/Documents/version.json
  mode: auto-replace
